In [1]:
import numpy as np
import pandas as pd, os, datetime

import matplotlib.pyplot as plt

# Import the loader function
os.chdir('/g/data/ng72/ms5578/ID_HW_BARRA')
from process_code import load_generation_data

Dask dashboard: /proxy/8787/status

2026-06-26 12:33:28,728 - distributed.shuffle._scheduler_plugin - WARNING - Shuffle 3bed0ad80cfb8170b39164e0292167f3 initialized by task ('shuffle-transfer-3bed0ad80cfb8170b39164e0292167f3', 370) executed on worker tcp://127.0.0.1:37561
2026-06-26 12:33:50,052 - distributed.shuffle._scheduler_plugin - WARNING - Shuffle 3bed0ad80cfb8170b39164e0292167f3 deactivated due to stimulus 'task-finished-1782441230.0063052'

In [2]:
data, info = load_generation_data(
    sdate="2009-07-01",
    edate="2024-06-30",
    mode="daily",
    ftype=["Wind"],
    apply_remove_negatives=True,
    apply_remove_wind_zeros=True,
    apply_min_heatwave_days=True,
    min_heatwave_days_threshold=20,
    apply_clear_agc=False
)

Read gen_details & hw_tseries with Dask: 0.27 sec
Select group: 0.03 sec
--- Starting Dask-Native Process ---

/g/data/ng72/ms5578/ID_HW_BARRA/process_code.py:168: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  grp_pd_jittered = grp_pd.groupby(['lat', 'lon'], group_keys=False).apply(

Starting final Dask compute...
Dask compute finished.

--- DASK TIMING REPORT ---
duid_setup: 0.00 seconds
csv_bulk_read: 1.99 seconds
filter_and_clean: 0.02 seconds
type_conversion_and_dropna: 0.07 seconds
date_filter: 0.02 seconds
hw_tseries_filter: 0.04 seconds
aggregate_daily: 0.12 seconds
jitter: 1.04 seconds
final_merge: 0.07 seconds
compute: 40.38 seconds
--- END REPORT ---

Process group: 49.49 sec

--- DEBUG: Calculated Heatwave Days per Generator ---
DUID
MEWF1       236
COOPGWF1    148
WRWF1       146
SAPHWF1     129
MUSSELR1    112
BODWF1       91
GRANWF1      84
MTGELWF1     60
STWF1        58
BALDHWF1     57
TARALGA1     54
LKBONNY2     52
KABANWF1     52
WOODLWN1     50
HDWF2        48
BOCORWF1     48
HDWF3        48
HDWF1        48
CROOKWF2     48
LKBONNY3     47
LGAPWF1      45
GUNNING1     45
GULLRWF1     45
NBHWF1       42
DULAWF1      41
HALLWF2      41
HALLWF1      41
CROWLWF1     40
CRURWF1      39
KIATAWF1     38
CLEMGPWF     38
MACARTH1     37
WATERLWF     36
WGWF1        36
SNOWNTH1     35
CHYTWF1      35
KEPWF1       34
SNOWTWN1     31
SNOWSTH1     30
OAKLAND1     29
MUWAWF1      29
ARWF1        27
WPWF         27
BULGANA1     25
CTHLWF1      25
YENDWF1      24
FLYCRKWF     24
BLUFF1       24
LGAPWF2      24
CNUNDAWF     23
LKBONNY1     23
SALTCRK1     23
MERCER01     22
PAREPW1      19
BANGOWF1     19
STARHLWF     19
GULLRWF2     19
CATHROCK     17
DUNDWF2      16
BRYB1WF1     16
ELAINWF1     16
DUNDWF1      16
DUNDWF3      16
COLWF01      15
BANGOWF2     14
MOORAWF1     13
RYEPARK1     11
MTMILLAR      9
STOCKYD1      9
MUWAWF2       4
MRTLSWF1      4
BRYB2WF2      3
Name: date, dtype: int64
--- END DEBUG ---

INFO: Applying 'min_heatwave_days' filter. Keeping 53 of 72 generators.
Filters: 0.22 sec

In [3]:
df = data.copy()

df["year"] = pd.to_datetime(df["time"]).dt.year
first_year = (
    df.groupby("DUID", as_index=False)["year"]
      .min()
      .rename(columns={"year": "first_year"})
)

print(first_year)

        DUID  first_year
0      ARWF1        2016
1   BALDHWF1        2015
2     BLUFF1        2011
3   BOCORWF1        2014
4     BODWF1        2018
5   BULGANA1        2020
6    CHYTWF1        2020
7   CLEMGPWF        2009
8   CNUNDAWF        2021
9   COOPGWF1        2019
10  CROOKWF2        2018
11  CROWLWF1        2018
12   CRURWF1        2020
13   CTHLWF1        2020
14   DULAWF1        2023
15  FLYCRKWF        2023
16   GRANWF1        2019
17  GULLRWF1        2013
18  GUNNING1        2011
19   HALLWF1        2009
20   HALLWF2        2009
21     HDWF1        2016
22     HDWF2        2017
23     HDWF3        2017
24  KABANWF1        2022
25    KEPWF1        2021
26  KIATAWF1        2017
27   LGAPWF1        2019
28   LGAPWF2        2021
29  LKBONNY1        2021
30  LKBONNY2        2009
31  LKBONNY3        2010
32  MACARTH1        2012
33  MERCER01        2013
34     MEWF1        2018
35  MTGELWF1        2018
36  MUSSELR1        2013
37   MUWAWF1        2019
38    NBHWF1        2010
39  OAKLAND1        2011
40  SALTCRK1        2018
41   SAPHWF1        2017
42  SNOWNTH1        2013
43  SNOWSTH1        2013
44  SNOWTWN1        2009
45     STWF1        2018
46  TARALGA1        2014
47  WATERLWF        2010
48     WGWF1        2018
49  WOODLWN1        2011
50      WPWF        2021
51     WRWF1        2017
52   YENDWF1        2019

In [19]:
counts = (
    df.groupby("DUID")["EHF_flag"]
      .value_counts()
      .unstack(fill_value=0)
      .rename(columns={0: "baseline", 1: "heatwave"})
      .reset_index()
)

print(counts)

EHF_flag      DUID  baseline  heatwave
0            ARWF1      1797        27
1         BALDHWF1      1770        57
2           BLUFF1      1803        24
3         BOCORWF1      1779        48
4           BODWF1      1735        91
5         BULGANA1      1472        25
6          CHYTWF1      1490        35
7         CLEMGPWF      1783        38
8         CNUNDAWF       912        23
9         COOPGWF1      1679       148
10        CROOKWF2      1779        48
11        CROWLWF1      1782        40
12         CRURWF1      1276        39
13         CTHLWF1      1612        25
14         DULAWF1       413        41
15        FLYCRKWF       304        24
16         GRANWF1      1588        84
17        GULLRWF1      1782        45
18        GUNNING1      1780        45
19         HALLWF1      1782        41
20         HALLWF2      1785        41
21           HDWF1      1778        48
22           HDWF2      1779        48
23           HDWF3      1777        48
24        KABANWF1       592        52
25          KEPWF1      1071        34
26        KIATAWF1      1789        38
27         LGAPWF1      1782        45
28         LGAPWF2       906        24
29        LKBONNY1       912        23
30        LKBONNY2      1752        52
31        LKBONNY3      1756        47
32        MACARTH1      1786        37
33        MERCER01      1801        22
34           MEWF1      1591       236
35        MTGELWF1      1758        60
36        MUSSELR1      1715       112
37         MUWAWF1      1796        29
38          NBHWF1      1782        42
39        OAKLAND1      1777        29
40        SALTCRK1      1802        23
41         SAPHWF1      1697       129
42        SNOWNTH1      1792        35
43        SNOWSTH1      1797        30
44        SNOWTWN1      1793        31
45           STWF1      1768        58
46        TARALGA1      1773        54
47        WATERLWF      1791        36
48           WGWF1      1791        36
49        WOODLWN1      1777        50
50            WPWF       908        27
51           WRWF1      1681       146
52         YENDWF1      1800        24

In [20]:
details = first_year.merge(counts[['DUID','heatwave','baseline']], on='DUID')

In [21]:
details = details.merge(info[['station_name','region','DUID']], on='DUID')

In [22]:
details.to_csv("data/output/wind_chapter/wind_details_table.csv")

In [23]:
base = info[["DUID","region","lat","lon"]]
base

        DUID region        lat         lon
0      ARWF1   VIC1 -37.238518  143.079431
1   BALDHWF1   VIC1 -38.790800  145.927700
4     BLUFF1    SA1 -33.369331  138.982476
6   BOCORWF1   NSW1 -36.576955  149.125867
7     BODWF1   NSW1 -32.414600  149.099795
11  BULGANA1   VIC1 -37.118103  142.960530
17   CHYTWF1   VIC1 -37.099382  145.267835
18  CLEMGPWF    SA1 -33.508568  138.119175
19  CNUNDAWF    SA1 -37.760253  140.403311
22  COOPGWF1   QLD1 -26.733227  151.472270
24  CROOKWF2   NSW1 -34.516500  149.542480
25  CROWLWF1   VIC1 -37.121560  143.153715
26   CRURWF1   NSW1 -33.005358  149.616812
27   CTHLWF1   TAS1 -42.159931  146.708927
30   DULAWF1   QLD1 -26.637084  149.871046
35  FLYCRKWF   NSW1 -33.516622  149.052132
38   GRANWF1   TAS1 -41.782720  145.048720
41  GULLRWF1   NSW1 -34.614456  149.459531
43  GUNNING1   NSW1 -34.697734  149.386126
44   HALLWF1    SA1 -33.348652  138.751659
45   HALLWF2    SA1 -33.348652  138.751659
46     HDWF1    SA1 -33.042878  138.556285
47     HDWF2    SA1 -33.042878  138.556285
48     HDWF3    SA1 -33.042839  138.556216
50  KABANWF1   QLD1 -17.560364  145.413271
51    KEPWF1   QLD1 -20.938150  144.371336
52  KIATAWF1   VIC1 -36.396583  141.747383
53   LGAPWF1    SA1 -32.564508  137.557192
54   LGAPWF2    SA1 -32.564508  137.557192
55  LKBONNY1    SA1 -37.781546  140.405792
56  LKBONNY2    SA1 -37.814894  140.419499
57  LKBONNY3    SA1 -37.750496  140.393029
58  MACARTH1   VIC1 -38.064804  142.184360
60  MERCER01   VIC1 -37.841111  143.871111
61     MEWF1   QLD1 -17.167500  145.387370
65  MTGELWF1   VIC1 -38.258691  143.801944
67  MUSSELR1   TAS1 -40.779811  148.009739
68   MUWAWF1   VIC1 -36.433261  142.318190
70    NBHWF1    SA1 -33.252576  138.712289
71  OAKLAND1   VIC1 -37.687059  142.546725
75  SALTCRK1   VIC1 -37.926755  142.771479
76   SAPHWF1   NSW1 -29.699726  151.411940
77  SNOWNTH1    SA1 -33.713956  138.140174
78  SNOWSTH1    SA1 -33.830164  138.118444
79  SNOWTWN1    SA1 -33.711237  138.145557
83     STWF1   NSW1 -31.806761  141.268646
84  TARALGA1   NSW1 -34.427076  149.857640
88  WATERLWF    SA1 -34.001025  138.910932
90     WGWF1    SA1 -33.393049  138.844777
93  WOODLWN1   NSW1 -35.086060  149.571606
95      WPWF    SA1 -35.110350  137.705778
96     WRWF1   NSW1 -29.846500  151.573260
99   YENDWF1   VIC1 -37.631438  144.020788

In [24]:
clustered_info = pd.read_csv("/g/data/ng72/ms5578/ID_HW_BARRA/data/preprocess/wind_spatial_clusters.csv")
profs = pd.read_csv("/g/data/ng72/ms5578/ID_HW_BARRA/data/preprocess/wind_profile_clusters.csv")
loc_df = clustered_info[["DUID", "lat","lon","cluster_name"]]
loc_df = pd.merge(loc_df,profs[["DUID","profile_name"]],on='DUID')
loc_df = pd.merge(loc_df,info[["DUID","region"]],on='DUID')
loc_df = pd.merge(loc_df,details[["DUID","first_year","heatwave","baseline"]],on='DUID')
loc_df

,DUID,lat,lon,cluster_name,profile_name,region,first_year,heatwave,baseline
0,ARWF1,-37.238518,143.079431,West Victoria,Minimal change,VIC1,2016,27,1797
1,BALDHWF1,-38.790800,145.927700,Bass Strait,Minimal change,VIC1,2015,57,1770
2,BLUFF1,-33.369331,138.982476,South Australia,Minimal change,SA1,2011,24,1803
3,BOCORWF1,-36.576955,149.125867,Alpine NSW,Minimal change,NSW1,2014,48,1779
4,BODWF1,-32.414600,149.099795,Alpine NSW,Minimal change,NSW1,2018,91,1735
5,BULGANA1,-37.118103,142.960530,West Victoria,Daytime increase,VIC1,2020,25,1472
6,CHYTWF1,-37.099382,145.267835,West Victoria,Minimal change,VIC1,2020,35,1490
7,CLEMGPWF,-33.508568,138.119175,South Australia,Morning peak,SA1,2009,38,1783
8,CNUNDAWF,-37.760253,140.403311,West Victoria,Daytime increase,SA1,2021,23,912
9,COOPGWF1,-26.733227,151.472270,Eastern Central,All-day reduction,QLD1,2019,148,1679
10,CROOKWF2,-34.516500,149.542480,Alpine NSW,Minimal change,NSW1,2018,48,1779
11,CROWLWF1,-37.121560,143.153715,West Victoria,Minimal change,VIC1,2018,40,1782
12,CRURWF1,-33.005358,149.616812,Alpine NSW,Minimal change,NSW1,2020,39,1276
13,CTHLWF1,-42.159931,146.708927,Bass Strait,All-day reduction,TAS1,2020,25,1612
14,DULAWF1,-26.637084,149.871046,Eastern Central,Daytime increase,QLD1,2023,41,413
15,FLYCRKWF,-33.516622,149.052132,Alpine NSW,Minimal change,NSW1,2023,24,304
16,GRANWF1,-41.782720,145.048720,Bass Strait,Minimal change,TAS1,2019,84,1588
17,GULLRWF1,-34.614456,149.459531,Alpine NSW,Minimal change,NSW1,2013,45,1782
18,GUNNING1,-34.697734,149.386126,Alpine NSW,Minimal change,NSW1,2011,45,1780
19,HALLWF1,-33.348652,138.751659,South Australia,Minimal change,SA1,2009,41,1782
20,HALLWF2,-33.348652,138.751659,South Australia,Minimal change,SA1,2009,41,1785
21,HDWF1,-33.042878,138.556285,South Australia,Morning peak,SA1,2016,48,1778
22,HDWF2,-33.042878,138.556285,South Australia,Morning peak,SA1,2017,48,1779
23,HDWF3,-33.042839,138.556216,South Australia,Morning peak,SA1,2017,48,1777
24,KABANWF1,-17.560364,145.413271,North Queensland,Extreme lows,QLD1,2022,52,592
25,KEPWF1,-20.938150,144.371336,North Queensland,All-day reduction,QLD1,2021,34,1071
26,KIATAWF1,-36.396583,141.747383,West Victoria,Minimal change,VIC1,2017,38,1789
27,LGAPWF1,-32.564508,137.557192,South Australia,All-day reduction,SA1,2019,45,1782
28,LGAPWF2,-32.564508,137.557192,South Australia,Morning peak,SA1,2021,24,906
29,LKBONNY1,-37.781546,140.405792,West Victoria,Daytime increase,SA1,2021,23,912
30,LKBONNY2,-37.814894,140.419499,West Victoria,Minimal change,SA1,2009,52,1752
31,LKBONNY3,-37.750496,140.393029,West Victoria,Daytime increase,SA1,2010,47,1756
32,MACARTH1,-38.064804,142.184360,West Victoria,Minimal change,VIC1,2012,37,1786
33,MERCER01,-37.841111,143.871111,West Victoria,Minimal change,VIC1,2013,22,1801
34,MEWF1,-17.167500,145.387370,North Queensland,Extreme lows,QLD1,2018,236,1591
35,MTGELWF1,-38.258691,143.801944,West Victoria,Minimal change,VIC1,2018,60,1758
36,MUSSELR1,-40.779811,148.009739,Bass Strait,Minimal change,TAS1,2013,112,1715
37,MUWAWF1,-36.433261,142.318190,West Victoria,Daytime increase,VIC1,2019,29,1796
38,NBHWF1,-33.252576,138.712289,South Australia,Minimal change,SA1,2010,42,1782
39,OAKLAND1,-37.687059,142.546725,West Victoria,Minimal change,VIC1,2011,29,1777
40,SALTCRK1,-37.926755,142.771479,West Victoria,Morning peak,VIC1,2018,23,1802
41,SAPHWF1,-29.699726,151.411940,Eastern Central,Minimal change,NSW1,2017,129,1697
42,SNOWNTH1,-33.713956,138.140174,South Australia,Morning peak,SA1,2013,35,1792
43,SNOWSTH1,-33.830164,138.118444,South Australia,Morning peak,SA1,2013,30,1797
44,SNOWTWN1,-33.711237,138.145557,South Australia,Morning peak,SA1,2009,31,1793
45,STWF1,-31.806761,141.268646,South Australia,All-day reduction,NSW1,2018,58,1768
46,TARALGA1,-34.427076,149.857640,Alpine NSW,Minimal change,NSW1,2014,54,1773
47,WATERLWF,-34.001025,138.910932,South Australia,Morning peak,SA1,2010,36,1791
48,WGWF1,-33.393049,138.844777,South Australia,Daytime increase,SA1,2018,36,1791
49,WOODLWN1,-35.086060,149.571606,Alpine NSW,Daytime increase,NSW1,2011,50,1777
50,WPWF,-35.110350,137.705778,South Australia,Daytime increase,SA1,2021,27,908
51,WRWF1,-29.846500,151.573260,Eastern Central,Minimal change,NSW1,2017,146,1681
52,YENDWF1,-37.631438,144.020788,West Victoria,Morning peak,VIC1,2019,24,1800

In [25]:
loc_df.to_csv("data/output/wind_chapter/wind_loc_table.csv")